services:
  - type: web
    name: lexai-production
    runtime: python
    plan: free

    buildCommand: pip install -r requirements.txt

    startCommand: gunicorn app:app

    envVars:
      - key: GROQ_API_KEY
        sync: false